#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>

#define MAX 100
#define MIN 0
#define TRIALS 10

int guessInput(char s [], int size);

int main(){

    //generate random number

    srand(time(NULL));   // Initialization, should only be called once.
    int r = (rand() % (MAX +1) ) + MIN;      // Returns a pseudo-random integer between 0 and RAND_MAX.
    //printf ("%i\n",r);

    int tCount = 0; // initialize a counter for trials
    char guess[20]; // initialize variable for user's guess
    int len, num;

    printf("GAME:\nTry to find a secret random number generated by the PC from %i to %i!\nYou have %i trials.\nGood luck!\n", MIN, MAX, TRIALS);

    do {
        //ask user input with entry validation
        do{
            printf("\nTrial N.%i\nEnter your guess from 0 to 100: ", tCount + 1);
            scanf(" %s", &guess);
            len = strlen(guess);
        } while (guessInput(guess, len) < len);

        num = atoi(guess); // convert the input string into int

        // check the guess

        if (num == r){
            printf("Congratulation, you find it!\nYou did it in %i trials!\n", tCount+1);
            break;
        }else if (num < r){
            printf("Wrong number, it is higher. Try again!\n");
            tCount++;
        }else if (num > r){
            printf("Wrong number, it is lower. Try again!\n");
            tCount++;
        }
    } while (tCount < TRIALS);
    if (tCount >= TRIALS)
        printf("\nYou loose! Your trials are over!\n");
}


int guessInput(char s [], int size){
    int count = 0;
    if (size < 3 && size > 0){
        for (int i = 0; i < size; i++){
            if ((s[i] >= '0' && s[i] <= '9')){
                count++;
            }else{
                printf("Invalid input!\n");
                break;
            }
        }
    }else{
        printf("Invalid input!\n");
    }
    return count;
}